DjangoHH/DjangoHH/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers, serializers, viewsets
from parserhhapp.api_views import CitiesViewSet, SkillsViewSet, CitiesSalaryViewSet
from parserhhapp.views import cloud

router = routers.DefaultRouter()
router.register(r'cities', CitiesViewSet)
router.register(r'skills', SkillsViewSet)
router.register(r'cities_salary', CitiesSalaryViewSet)




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('parserhhapp.urls', namespace='parser')),
    path('users/', include('usersapp.urls', namespace='users')),
    path('api-auth/', include('rest_framework.urls')),
    # path('cities-api/', include(router.urls)),
    path('api/v0/', include(router.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

# включаем возможность обработки картинок
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoHH/parserhhapp/urls.py
from django.urls import path
from parserhhapp import views



app_name = 'parserhhapp'

urlpatterns = [
    path('', views.create_pars, name='data'),
    path('index/', views.main_view, name='result'),
    path('post/<int:id>/', views.data_return, name='post'),
    path('city/', views.city_return, name='city'),
    path('posts/', views.create_post, name='post'),
    path('city_list/', views.CityListView.as_view(), name='city_list'),
    path('salary/', views.CitySalaryListView.as_view(), name='salary'),
    path('cloud/', views.cloud, name='cloud'),
    path('cloud_skill/', views.cloud_skill, name='cloud_skill'),
    path('city_list_detail/<int:pk>/', views.CityDetailView.as_view(), name='city_list_detail'),
    path('city_list_create/', views.CityCreateView.as_view(), name='city_list_create'),
    path('city_list_update/<int:pk>/', views.CityUpdateView.as_view(), name='city_list_update'),
    path('city_list_delete/<int:pk>/', views.CityDeleteView.as_view(), name='city_list_delete'),
    path('skill_list/', views.SkillListView.as_view(), name='skill_list'),
    path('skill_list_detail/<int:pk>/', views.SkillDetailView.as_view(), name='skill_list_detail'),
    path('skill_list_create/', views.SkillCreateView.as_view(), name='skill_list_create'),
    path('skill_list_update/<int:pk>/', views.SkillUpdateView.as_view(), name='skill_list_update'),
    path('skill_list_delete/<int:pk>/', views.SkillDeleteView.as_view(), name='skill_list_delete'),
    path('simple/', views.SimpleMainAjax.as_view(), name='simple_ajax'),

]

DjangoHH/parserhhapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from django.utils.functional import cached_property


class Skills(models.Model):
    name = models.TextField(max_length=300, verbose_name = 'навык')
    percent = models.CharField(max_length=30, verbose_name = 'доля')
    count = models.CharField(max_length=30, null=True, verbose_name = 'количество')

    class Meta:
        verbose_name = 'skill'
        verbose_name_plural = 'skills'

    @cached_property
    def skills_all_cached(self):
        skills_cached = Skills.objects.all()
        return skills_cached

    def __str__(self):
        return self.name

    def has_name(self):
        return self.name is None

    def has_percent(self):
        return self.percent is None

    def has_count(self):
        return self.count is None

    def some_method(self):
        return 'test'

    def __str__(self):
        return f'{self.name}, {self.percent}, {self.count}'

class Cities(models.Model):
    name = models.TextField(max_length=300, verbose_name = 'город')
    percent = models.CharField(max_length=30, verbose_name = 'доля')
    count = models.CharField(max_length=30, null=True, verbose_name = 'количество')
    image = models.ImageField(upload_to='coat', null=True, blank=True, max_length=500)


    class Meta:
        verbose_name = 'city'
        verbose_name_plural = 'cities'


    def __str__(self):
        return self.name

    def has_name(self):
        return self.name is None

    def has_percent(self):
        return self.percent is None

    def has_count(self):
        return self.count is None

    def has_image(self):
        return bool(self.image)

    def __str__(self):
        return f'{self.name}, {self.percent}, {self.count}'


class CitiesSalary(models.Model):
    name = models.TextField(max_length=300, verbose_name = 'город')
    percent = models.CharField(max_length=30, verbose_name = 'доля')
    count = models.CharField(max_length=30, null=True, verbose_name = 'количество')
    salary = models.CharField(max_length=300, verbose_name='зарплата')


    class Meta:
        verbose_name = 'city_salary'
        verbose_name_plural = 'city_salaries'


    def __str__(self):
        return self.name

    def has_name(self):
        return self.name is None

    def has_percent(self):
        return self.percent is None

    def has_count(self):
        return self.count is None

    def has_image(self):
        return bool(self.image)

    def __str__(self):
        return f'{self.name}, {self.percent}, {self.count} {self.salary}'


class SkillCloud(models.Model):
    # title = models.CharField(max_length=150)
    cover = models.ImageField(upload_to='images/')
    book = models.ImageField(upload_to='books/')

    # def __str__(self):
    #     return self.title
    class Meta:
        verbose_name = 'skill_cloud'
        verbose_name_plural = 'skill_clouds'

DjangoHH/parserhhapp/forms.py
from django import forms
from parserhhapp.models import Cities, Skills


class RequestForm(forms.Form):

    vacancy = forms.CharField(label='Профессия для парсинга', widget=forms.TextInput(attrs={'placeholder': 'профессия для парсинга', 'class': 'form-control', }))
    city = forms.CharField(label='Город для парсинга*', required=False, widget=forms.TextInput(attrs={'placeholder': 'название города', 'class': 'form-control', }))
    size = forms.IntegerField(label='Количество вакансий**', widget=forms.TextInput(attrs={'placeholder': 'количество вакансий', 'class': 'form-control', }))
    #
    # class Meta:
    #     model = Skills
    #     fields = '__all__'
    #     # exclude = ('image',)


class PostForm(forms.ModelForm):
    # name = forms.CharField(label='Город')
    name = forms.CharField(label='Город', widget=forms.TextInput(attrs={'placeholder': 'название города', 'class': 'form-control', }))
    percent = forms.CharField(label='доля', widget=forms.TextInput(attrs={'placeholder': 'доля в %', 'class': 'form-control', }))
    count = forms.IntegerField(label='количество', widget=forms.TextInput(attrs={'placeholder': 'количество', 'class': 'form-control', }))

    class Meta:
        model = Cities
        # fields = '__all__'
        exclude = ('image',)


class SkillForm(forms.Form):

    class Meta:
        model = Skills
        fields = '__all__'

DjangoHH/parserhhapp/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from parserhhapp.models import Cities, Skills, CitiesSalary, SkillCloud
from parserhhapp.forms import RequestForm, PostForm
from parserhhapp.parser_site import parser_site
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.cache import cache
from django.core.files.storage import FileSystemStorage




# Create your views here
def main_view(request):

    skills = cache.get('skills')
    if not skills:
        skills = Skills.objects.all()
        cache.set('skills', skills, 60)

    paginator = Paginator(skills, 5)

    page = request.GET.get('page')
    try:
        skills = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        skills = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        skills = paginator.page(paginator.num_pages)

    title = 'навыки'

    return render(request, 'parserhhapp/index.html', context={'skills': skills, 'title': title})

def city_return(request):
    cities = cache.get('cities')
    if not cities:
        cities = Cities.objects.all()
        cache.set('cities', cities, 60)

    paginator_city = Paginator(cities, 5)

    page = request.GET.get('page')
    try:
        cities = paginator_city.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        cities = paginator_city.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        cities = paginator_city.page(paginator_city.num_pages)

    title = 'города'

    return render(request, 'parserhhapp/citycoat.html', context={'cities': cities, 'title': title})
#создание формы
# получение данных если запрос POST, если нет, то отрисовка снова пустой формы,
# если да проверка на валидность, если норм, то заполнение данными если нет,
# то отрисока пустой формы

@login_required
def create_pars(request):
    if request.method == 'POST':
        # form = RequestForm(request.POST)
        form = RequestForm(request.POST, files=request.FILES)

        if form.is_valid():
            region = form.cleaned_data['city']
            pages = form.cleaned_data['size']
            proff = form.cleaned_data['vacancy']
            parser_site(pages, proff, region)
            return HttpResponseRedirect(reverse('parser:result'))

        else:
            title = '5'
            return render(request, 'parserhhapp/create.html', context={'form': form, 'title': title})
    else:
        form = RequestForm()
        title = 'запрос'
        return render(request, 'parserhhapp/create.html', context={'form': form, 'title': title})



def data_return(request, id):
    data = get_object_or_404(Skills, id=id)
    title = 'статистика'
    return render(request, 'parserhhapp/post.html', context={'data': data, 'title': title})

@user_passes_test(lambda u: u.is_superuser)
def create_post(request):
    if request.method == 'GET':
        form = PostForm()
        title = 'новый город'
        return render(request, 'parserhhapp/posts.html', context={'form': form, 'title': title})
    else:
        form = PostForm(request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('parser:city'))
        else:
            return render(request, 'parserhhapp/posts.html', context={'form': form})


class SkillListView(LoginRequiredMixin, ListView):
    model = Skills
    template_name = 'parserhhapp/skill_list.html'
    paginate_by = 5

class SkillDetailView(LoginRequiredMixin, DetailView):
    model = Skills
    template_name = 'parserhhapp/skill_list_detail.html'
    paginate_by = 5


class SkillCreateView(LoginRequiredMixin, CreateView):
    fields = '__all__'
    model = Skills
    success_url = reverse_lazy('parser:skill_list')
    template_name = 'parserhhapp/skill_list_create.html'
    paginate_by = 5


class SkillUpdateView(LoginRequiredMixin, UpdateView):
    fields = '__all__'
    model = Skills
    success_url = reverse_lazy('parser:skill_list')
    template_name = 'parserhhapp/skill_list_create.html'
    paginate_by = 5


class SkillDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'parserhhapp/skill_list_delete_confirm.html'
    model = Skills
    success_url = reverse_lazy('parser:skill_list')
    paginate_by = 5



class CityListView(LoginRequiredMixin, ListView):
    model = Cities
    template_name = 'parserhhapp/city_list.html'
    paginate_by = 5


class CityDetailView(LoginRequiredMixin, DetailView):
    model = Cities
    template_name = 'parserhhapp/city_list_detail.html'
    paginate_by = 5

class CityCreateView(LoginRequiredMixin, CreateView):
    fields = '__all__'
    model = Cities
    success_url = reverse_lazy('parser:city_list')
    template_name = 'parserhhapp/city_list_create.html'
    paginate_by = 5

class CityUpdateView(LoginRequiredMixin, UpdateView):
    fields = '__all__'
    model = Cities
    success_url = reverse_lazy('parser:city_list')
    template_name = 'parserhhapp/city_list_create.html'
    paginate_by = 5

class CityDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'parserhhapp/city_list_delete_confirm.html'
    model = Cities
    success_url = reverse_lazy('parser:city_list')
    paginate_by = 5


class SimpleMainAjax(TemplateView):
    template_name = 'parserhhapp/simple.html'


class CitySalaryListView(LoginRequiredMixin, ListView):
    model = CitiesSalary
    template_name = 'parserhhapp/salary.html'
    # paginate_by = 5


def cloud(request):
    data = SkillCloud.objects.all()


    return render(request, 'parserhhapp/cloud.html', {'data': data})

def cloud_skill(request):
    data = SkillCloud.objects.all()

    return render(request, 'parserhhapp/cloud_skill.html', {'data': data})

DjangoHH/parserhhapp/templates/parserhhapp/city_list_create.html
{% extends 'base.html' %}

{% block title %}
    Создание города
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <p>Создание/редактирование города на CBV</p>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h3> {{ form.as_p }} </h3>


            <button type="submit" class="btn btn-primary" id="sendMessageButton">СОХРАНИТЬ</button>
            <a type="submit" class="btn btn-primary" href="{% url 'parser:city_list' %}">ОТМЕНА</a>
        </form>

    </div>
</div>


{% endblock %}

DjangoHH/parserhhapp/templates/parserhhapp/city_list_delete_confirm.html
{% extends 'base.html' %}

{% block title %}
{{object.name}}
{% endblock %}

{% block content %}
<ul>


            <h1>
                {{object.name}}
            </h1>



</ul>
            Вы уверены?
            <form method="post">
            {% csrf_token %}
<div>            <button type="submit" class="btn btn-danger">ДА</button>
 <a class="btn btn-primary text-uppercase" href="{% url 'parser:city_list' %}">ОТМЕНА</a></div>
        </form>



{% endblock %}

DjangoHH/parserhhapp/templates/parserhhapp/city_list_detail.html
{% extends 'base.html' %}

{% block title %}
{{object.name}}
{% endblock %}

{% block content %}
<ul>


            <h1> {{object.name}} </h1>
            <h5> Доля </h5>
            <h1> {{object.percent}} </h1>
            <h5> Количество упоминаний </h5>
            <h1> {{object.count}} </h1>
</ul>
<div>
<a class="btn btn-primary text-uppercase" href="{% url 'parser:city_list_update' pk=object.pk %}">Изменить</a>
<a class="btn btn-primary text-uppercase" href="{% url 'parser:city_list_delete' pk=object.pk %}">Удалить</a>

<a class="btn btn-primary text-uppercase" href="{% url 'parser:city_list' %}">Отмена</a>
</div>
{% endblock %}

DjangoHH/parserhhapp/templates/parserhhapp/citycoat.html
{% extends 'base.html' %}

{% block title %}
 Города
{% endblock %}

{% block content %}
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% for item in cities %}

                    <!-- Post preview-->
                    <div class="post-preview">
                            <img src="{{item.image}}" >
                            <h2 class="post-title"> {{item.name}} {{item.percent}} {{item.count}}</h2>
<!--                            <h3 class="post-subtitle">{{item.percent}} </h3>-->
<!--                            <h3 class="post-subtitle">{{item.count}} </h3>-->
                        </a>

                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    {% endfor %}

                                        <!-- Pager-->
                    <div class="clearfix">
                        <div class="pagination">

                        <span class="step-links">
                            {% if cities.has_previous %}
                                <a class="btn btn-primary float-right"
                                    href="?page={{ cities.previous_page_number }}">&larr; Назад</a>
                            {% endif %}

                                <span class="current">
                                    Page {{ cities.number }} of {{ cities.paginator.num_pages }}.
                                </span>

                            {% if cities.has_next %}

                                    <a class="btn btn-primary float-right"
                                       href="?page={{ cities.next_page_number }}">Вперед &rarr;</a>

                            {% endif %}


                             </span>
                        </div>
                    </div>
<!-- Pager-->

                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="{% url 'parser:data' %}">Данные для парсера HH.RU</a></div>
                </div>
            </div>
{% endblock %}

DjangoHH/parserhhapp/templates/parserhhapp/cloud.html
{% extends 'base.html' %}

{% block title %}
    Облако навыков и городов
{% endblock %}

{% block content %}



<!--{% for b in data %}-->
<!--<a href="{{ b.book.url }}"></a>-->
<!--<br/>-->

         <img src="{{ b.book.url }}" width="1200" >
            <hr>
        <img src="{{ b.cover.url }}" width="1200" >




<!--{% endfor %}-->




{% endblock %}

DjangoHH/parserhhapp/templates/parserhhapp/create.html
{% extends 'base.html' %}

{% block title %}
    Данные для запроса
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <p>Данные для парсера</p>

        <form method="post">
            {% csrf_token %}
            <h3> {{ form.as_p }} </h3>
            <button type="submit" class="btn btn-primary" id="sendMessageButton">ПАРСИМ</button>
        </form>

            *)  - необязательный параметр
            **) - желательно не более 100
    </div>
</div>


{% endblock %}

DjangoHH/parserhhapp/templates/parserhhapp/post.html
{% extends 'base.html' %}

{% block title %}
{{data.name}}
{% endblock %}

{% block content %}

                    <h1> {{data.name}} </h1>

                    <div class="col-md-10 col-lg-8 col-xl-7">
                    <h5 class="section-heading">Доля</h5>

                   <h2 class="post-subtitle"> {{data.percent}}  </h2>
                    <h5 class="section-heading">Количество упоминаний</h5>

                   <h2 class="post-subtitle"> {{data.count}}  </h2>

                    </div>

<div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="{% url 'parser:result' %}">Результаты - навыки</a></div>


{% endblock %}

DjangoHH/parserhhapp/templates/parserhhapp/posts.html
{% extends 'base.html' %}

{% block title %}
    Создание города
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <p>Данные для создания данных по городу</p>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h3> {{ form.as_p }} </h3>


            <button type="submit" class="btn btn-primary" id="sendMessageButton">СОХРАНИТЬ</button>
        </form>

    </div>
</div>


{% endblock %}

DjangoHH/parserhhapp/templates/parserhhapp/salary.html
{% extends 'base.html' %}

{% block title %}
    Рейтинг зарплат
{% endblock %}

{% block content %}
    <ul>

        {% for item in object_list %}

            <li>
                <div class="container">
                    <h2 class="post-title"> {{ item.name}} </h2>
                    <h4 class="post-subtitle">{{ item.salary}} р. </h4>

<!--                            <h3 class="post-subtitle">{{ item.percent}} </h3>-->
<!--                            <h3 class="post-subtitle">{{ item.count}} </h3>-->
<!--                    {{item.name}} {{item.salary}} {{item.count}} {{item.percent}}-->

                </div>
            </li>
        {% endfor %}


    </ul>

{% endblock %}

DjangoHH/parserhhapp/templates/parserhhapp/simple.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>simple.html</title>
</head>
<body>
    <button type="button" id="cities">Города</button>
    <hr>
    <button type="button" id="skills">Навыки</button>
    <hr>
    <button type="button" id="all">Все</button>

    <ul id="div_cities"></ul>
    <ul id="div_skills"></ul>


<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/my_ajax.js' %}"></script>

</body>
</html>

DjangoHH/parserhhapp/templates/parserhhapp/skill_list.html
{% extends 'base.html' %}

{% block title %}
    Список навыков
{% endblock %}

{% block content %}
    <ul>
        {% for item in object_list %}

            <li>
                <a href="{% url 'parser:skill_list_detail' pk=item.pk %}">
                    <h2>
                        {{item.name}}
                    </h2>
                    <h5>
                    <a href="{% url 'parser:skill_list_update' pk=item.pk %}">
                            Изменить
                    </a>
                        /
                    <a href="{% url 'parser:skill_list_delete' pk=item.pk %}">
                            Удалить

                    </a>
                    </h5>


            </li>
        {% endfor %}

        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a class="btn btn-primary float-right"
                            href="?page=1">&laquo; Первая</a>
                    <a class="btn btn-primary float-right"
                            href="?page={{ page_obj.previous_page_number }}">&larr; Назад</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a class="btn btn-primary float-right"
                            href="?page={{ page_obj.next_page_number }}">Вперед &rarr;</a>
                    <a class="btn btn-primary float-right"
                            href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
                {% endif %}
            </span>
        </div>



    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="{% url 'parser:skill_list_create' %}">Создать</a></div>



    </ul>

{% endblock %}

DjangoHH/parserhhapp/templates/parserhhapp/skill_list_create.html
{% extends 'base.html' %}

{% block title %}
    Создание навыка
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <p>Создание/редактирование навыка на CBV</p>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h3> {{ form.as_p }} </h3>


            <button type="submit" class="btn btn-primary" id="sendMessageButton">СОХРАНИТЬ</button>
            <a type="submit" class="btn btn-primary" href="{% url 'parser:skill_list' %}">ОТМЕНА</a>
        </form>

    </div>
</div>


{% endblock %}

DjangoHH/parserhhapp/templates/parserhhapp/skill_list_delete_confirm.html
{% extends 'base.html' %}

{% block title %}
{{object.name}}
{% endblock %}

{% block content %}
<ul>


            <h1>
                {{object.name}}
            </h1>



</ul>
            Вы уверены?
            <form method="post">
            {% csrf_token %}
<div>            <button type="submit" class="btn btn-danger">ДА</button>
 <a class="btn btn-primary text-uppercase" href="{% url 'parser:skill_list' %}">ОТМЕНА</a></div>
        </form>



{% endblock %}

DjangoHH/parserhhapp/templates/parserhhapp/skill_list_detail.html
{% extends 'base.html' %}

{% block title %}
{{object.name}}
{% endblock %}

{% block content %}
<ul>

            <h1> {{object.name}} </h1>
            <h5> Доля </h5>
            <h1> {{object.percent}} </h1>
            <h5> Количество упоминаний </h5>
            <h1> {{object.count}} </h1>
</ul>
<div>
<a class="btn btn-primary text-uppercase" href="{% url 'parser:skill_list_update' pk=object.pk %}">Изменить</a>
<a class="btn btn-primary text-uppercase" href="{% url 'parser:skill_list_delete' pk=object.pk %}">Удалить</a>

<a class="btn btn-primary text-uppercase" href="{% url 'parser:skill_list' %}">Отмена</a>
</div>
{% endblock %}