DjangoHH/DjangoHH/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers, serializers, viewsets
from parserhhapp.api_views import CitiesViewSet, SkillsViewSet, CitiesSalaryViewSet
from parserhhapp.views import cloud

router = routers.DefaultRouter()
router.register(r'cities', CitiesViewSet)
router.register(r'skills', SkillsViewSet)
router.register(r'cities_salary', CitiesSalaryViewSet)




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('parserhhapp.urls', namespace='parser')),
    path('users/', include('usersapp.urls', namespace='users')),
    path('api-auth/', include('rest_framework.urls')),
    # path('cities-api/', include(router.urls)),
    path('api/v0/', include(router.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

# включаем возможность обработки картинок
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoHH/parserhhapp/urls.py
from django.urls import path
from parserhhapp import views



app_name = 'parserhhapp'

urlpatterns = [
    path('', views.create_pars, name='data'),
    path('index/', views.main_view, name='result'),
    path('post/<int:id>/', views.data_return, name='post'),
    path('city/', views.city_return, name='city'),
    path('posts/', views.create_post, name='post'),
    path('city_list/', views.CityListView.as_view(), name='city_list'),
    path('salary/', views.CitySalaryListView.as_view(), name='salary'),
    path('cloud/', views.cloud, name='cloud'),
    path('cloud_skill/', views.cloud_skill, name='cloud_skill'),
    path('city_list_detail/<int:pk>/', views.CityDetailView.as_view(), name='city_list_detail'),
    path('city_list_create/', views.CityCreateView.as_view(), name='city_list_create'),
    path('city_list_update/<int:pk>/', views.CityUpdateView.as_view(), name='city_list_update'),
    path('city_list_delete/<int:pk>/', views.CityDeleteView.as_view(), name='city_list_delete'),
    path('skill_list/', views.SkillListView.as_view(), name='skill_list'),
    path('skill_list_detail/<int:pk>/', views.SkillDetailView.as_view(), name='skill_list_detail'),
    path('skill_list_create/', views.SkillCreateView.as_view(), name='skill_list_create'),
    path('skill_list_update/<int:pk>/', views.SkillUpdateView.as_view(), name='skill_list_update'),
    path('skill_list_delete/<int:pk>/', views.SkillDeleteView.as_view(), name='skill_list_delete'),
    path('simple/', views.SimpleMainAjax.as_view(), name='simple_ajax'),

]

DjangoHH/usersapp/urls.py
from django.urls import path
from usersapp import views
from django.contrib.auth.views import LogoutView



app_name = 'usersapp'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('profile/<int:pk>/', views.UserDetailView.as_view(), name='profile'),
    path('updatetoken/', views.update_token, name='update_token'),
    path('update-token-ajax/', views.update_token_ajax),

]

DjangoHH/templates/base.html
{% load static %}
{% load str_extensions %}

<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />


        <title>{% block title %}{% endblock %}</title>

        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-15 px-lg-10">


                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'parser:data' %}">Данные для парсера HH.RU</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'parser:result' %}">Результаты - навыки</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'parser:city' %}">Результаты - города</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'parser:post' %}">Создание города</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'parser:skill_list' %}">Список навыков на CBV</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'parser:city_list' %}">Список городов на CBV</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'parser:salary' %}">Рейтинг зарплат</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'parser:cloud' %}">ОБЛАКО</a></li>
<!--                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'parser:cloud_skill' %}">Облако навыков</a></li>-->
                        {% if user.is_authenticated %}
                        <li class="nav-item">Привет, <a href="{% url 'users:profile' pk=user.pk %}">{{user.username}}</a>
                            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'users:logout' %}">Выход</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'users:login' %}">Вход</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'users:register' %}">Регистрация</a></li>
                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Парсер HH</h1>
                            <h2>{{title|capitalize}}</h2>
                            <span class="subheading"></span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            {% block content %}{% endblock %}
        </div>


        <!-- Footer-->
        <footer class="border-top">
<!--            <div class="container px-4 px-lg-5">-->
<!--                <div class="row gx-4 gx-lg-5 justify-content-center">-->
<!--                    <div class="col-md-10 col-lg-8 col-xl-7">-->
<!--                        <ul class="list-inline text-center">-->
<!--                            <li class="list-inline-item">-->
<!--                                <a href="#!">-->
<!--                                    <span class="fa-stack fa-lg">-->
<!--                                        <i class="fas fa-circle fa-stack-2x"></i>-->
<!--                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>-->
<!--                                    </span>-->
<!--                                </a>-->
<!--                            </li>-->
<!--                            <li class="list-inline-item">-->
<!--                                <a href="#!">-->
<!--                                    <span class="fa-stack fa-lg">-->
<!--                                        <i class="fas fa-circle fa-stack-2x"></i>-->
<!--                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>-->
<!--                                    </span>-->
<!--                                </a>-->
<!--                            </li>-->
<!--                            <li class="list-inline-item">-->
<!--                                <a href="#!">-->
<!--                                    <span class="fa-stack fa-lg">-->
<!--                                        <i class="fas fa-circle fa-stack-2x"></i>-->
<!--                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>-->
<!--                                    </span>-->
<!--                                </a>-->
<!--                            </li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>  -->
<!--            </div>-->

            <div class="small text-center text-muted fst-italic">
                <button type="button" id="btn-text" class="btn-info">
                    {{my_text}}
                </button>
            </div>
            <br />
<!--            <hr>-->
            <div
                    class="small text-center text-muted fst-italic">{{user.username}}
            </div>

        </footer>
<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/clean-blog.min.js' %}"></script>
<script src="{% static 'js/my.js' %}"></script>
<script src="{% static 'js/my_ajax.js' %}"></script>


    </body>
</html>