DjangoHH/DjangoHH/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers, serializers, viewsets
from parserhhapp.api_views import CitiesViewSet, SkillsViewSet, CitiesSalaryViewSet
from parserhhapp.views import cloud

router = routers.DefaultRouter()
router.register(r'cities', CitiesViewSet)
router.register(r'skills', SkillsViewSet)
router.register(r'cities_salary', CitiesSalaryViewSet)




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('parserhhapp.urls', namespace='parser')),
    path('users/', include('usersapp.urls', namespace='users')),
    path('api-auth/', include('rest_framework.urls')),
    # path('cities-api/', include(router.urls)),
    path('api/v0/', include(router.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

# включаем возможность обработки картинок
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoHH/usersapp/urls.py
from django.urls import path
from usersapp import views
from django.contrib.auth.views import LogoutView



app_name = 'usersapp'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('profile/<int:pk>/', views.UserDetailView.as_view(), name='profile'),
    path('updatetoken/', views.update_token, name='update_token'),
    path('update-token-ajax/', views.update_token_ajax),

]

DjangoHH/usersapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class ParsUser(AbstractUser):
    email = models.EmailField(unique=True)

DjangoHH/usersapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import ParsUser

class RegForm(UserCreationForm):
    class Meta:
        model = ParsUser
        fields = ('username', 'password1', 'password2', 'email')

DjangoHH/usersapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.views import LoginView, LogoutView
from .forms import RegForm
from django.views.generic import CreateView, DetailView
from .models import ParsUser
from django.urls import reverse, reverse_lazy
from rest_framework.authtoken.models import Token
from django.http import JsonResponse


# Create your views here.
class UserLoginView(LoginView):
    template_name = 'usersapp/login.html'

class UserCreateView(CreateView):
    model = ParsUser
    template_name = 'usersapp/register.html'
    form_class = RegForm
    success_url = reverse_lazy('users:login')

class UserDetailView(DetailView):
    template_name = 'usersapp/profile.html'
    model = ParsUser

def update_token(request):
    user = request.user
    try:
        user.auth_token.delete()
        Token.objects.create(user=user)
    except:
        print('Нет')
        # создать
        Token.objects.create(user=user)
    return HttpResponseRedirect(reverse('users:profile', kwargs={'pk': user.pk}))

def update_token_ajax(request):
    user = request.user
    # если уже есть
    if user.auth_token:
        # обновить
        user.auth_token.delete()
        token = Token.objects.create(user=user)
    else:
        # создать
        token = Token.objects.create(user=user)
    return JsonResponse({'key': token.key})

DjangoHH/usersapp/templates/usersapp/login.html
{% extends 'base.html' %}

{% block title %}
    Вход
{% endblock %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Войти</button>

    </form>


{% endblock %}

DjangoHH/usersapp/templates/usersapp/profile.html
{% extends "base.html" %}

{% block title %}
Профиль
{% endblock %}

{% block content %}
    Профиль пользователя {{object.username}}
    <hr>
    Токен:
<span id="token">{% if object.auth_token %} {{object.auth_token}} {% else %} не создан {% endif %}</span>

    <form action="{% url 'users:update_token' %}">
        <button type="submit" class="btn btn-primary">Refresh token</button>
    </form>
    <hr>
    <button type="button" id="ajax-btn" class="btn btn-primary">Refresh token ajax</button>

{% endblock %}

DjangoHH/usersapp/templates/usersapp/register.html
{% extends 'base.html' %}

{% block title %}
    Регистрация
{% endblock %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Зарегистроваться</button>

    </form>


{% endblock %}